name: widgetbook_challenge
description: A new Flutter project.

publish_to: 'none' 
version: 1.0.0+1

environment:
  sdk: ">=2.16.1 <3.0.0"

dependencies:
  argon_buttons_flutter: ^1.1.0
  confetti: ^0.7.0
  cupertino_icons: ^1.0.2

  flutter:
    sdk: flutter
  flutter_mobx: ^2.0.6+1
  mobx: ^2.0.7+5
  mocktail: ^0.3.0


dev_dependencies:
  flutter_test:
    sdk: flutter
  build_runner: ^2.2.0
  mobx_codegen: ^2.0.7
  very_good_analysis: ^2.4.0

flutter:
  uses-material-design: true